{% set version = "2.10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ontologyindex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ontologyIndex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ontologyIndex/ontologyIndex_{{ version }}.tar.gz
  sha256: c995d6d9df5ff9cfb81fb80f553fc0f392d2237ffa6dd8619fd8fbce745a3a42

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('ontologyIndex')"           # [not win]
    - "\"%R%\" -e \"library('ontologyIndex')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ontologyIndex
  license: GPL-2.0-or-later
  summary: "Functions for reading ontologies into R as lists and manipulating sets of ontological terms - 'ontologyX: A suite of R packages for working with ontological data', Greene et al 2017 <doi:10.1093/bioinformatics/btw763>."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - RJMW

# Package: ontologyIndex
# Type: Package
# Title: Functions for Reading Ontologies into R
# Version: 2.5
# Date: 2019-01-08
# Author: Daniel Greene <dg333@cam.ac.uk>
# Maintainer: Daniel Greene <dg333@cam.ac.uk>
# Description: Functions for reading ontologies into R as lists and manipulating sets of ontological terms - 'ontologyX: A suite of R packages for working with ontological data', Greene et al 2017 <doi:10.1093/bioinformatics/btw763>.
# License: GPL (>= 2)
# Depends: R (>= 3.1.0)
# Suggests: knitr, rmarkdown, ontologySimilarity, ontologyPlot
# VignetteBuilder: knitr
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2019-01-08 14:22:03 UTC; dg
# Repository: CRAN
# Date/Publication: 2019-01-08 16:30:06 UTC
