appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: kYAoLtvJ89KjYhfFYy4/i6Xk3oYXbrgVj7DjJFNH5PPJpdSgiXn/mUUQDyA6CRY3wGNJYrFjEdf9JbngLWVzjVhj3YWmocE5O/iX0qTRsWoznYyCcGMcwfJFbZgksbhUKPqwbIyKkQgeYunZ2cYRtsifYSnwXmOzMLdVJHFKUntfgVmmqox+wWChw4SpKBjytib9UgOe/o8qeap2k0jwFs2AHsDnAv2Dmo+G93sxbddj+N/MbSzq/sX7CAxeEMe9Xau8SUq1scQSNxaon7A4CAMh+PcrgoZNjnYa03mcdKTWg7lnLH169sh7C/Ctxqb+HOwO2AIS982kz6UwtOFbfF5lbxcBoKdJ3pn9QJsOXZXmAepvoxjxtKAE1HvS9LyYGEdpwXBTF8M9anCzMfXjuETiqnISyc6T09YjERbEScwW0cAPj7EGw4+NQUJuTq1QBeD4DzgxvCKEsUk0kXxIdtd4IqT7Ss1aAH0dl2zbFQZ22jZsmL39hq+10E6PP7vlFo52txb0XGKd7X/0g1hS0Ni1Wp+cRpN8Y/kD68ZbyRvFjEXgsN2TyDPYfCjVyn6cPLOdsnAIftXUjbktU3ffNCfbvE8WTAQRM1jeyKDFaFpdwaYZHs6ESDfKv/uvYMudlghq7IYiKOzgvgQnXjxhZ8WM30vqbwvGPyhMCD05oO4=
